version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=timecoder
    volumes:
      - "./mycustom.cnf:/etc/mysql/conf.d/custom.cnf"
  timecoder-api:
    image: spirogov/timecoder:1.3
    container_name: timecoder
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    links:
      - mysql
  ui:
    image: spirogov/timecoder-ui:1.3
    container_name: timecoder-ui
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    links:
      - timecoder-api
  gateway:
    image: spirogov/timecoder-gateway:0.0.15
    container_name: timecoder-gateway
    depends_on:
      - mysql
    ports:
      - 8086:5000
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    links:
      - timecoder-api