server:
  port: 5000

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    initialization-mode: always
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/timecoder?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
  
timecoderService:
  ribbon:
    listOfServers: http://localhost:8080

---
spring:
  profiles: prod
  datasource:
    initialization-mode: always
    username: root
    password: admin
    url: jdbc:mysql://mysql:3306/timecoder?useUnicode=yes&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

timecoderService:
  ribbon:
    listOfServers: http://timecoder-api:8080
